version: '3.8'

networks:
  connect-db:
    driver: bridge

services:

  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U '$POSTGRES_USER' -d '$POSTGRES_DB''" ]
      interval: 30s
      timeout: 5s
      retries: 8
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - connect-db

  server:
    container_name: authentication
    build:
      context: .
    ports:
      - '3333:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - connect-db
    env_file:
      - .env

volumes:
  db:
